lirc: temporary fix build engima2
/usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:519: undefined reference to `cTimeMs::cTimeMs(int)'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:520: undefined reference to `cTimeMs::cTimeMs(int)'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:583: undefined reference to `cTimeMs::Elapsed() const'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:565: undefined reference to `cTimeMs::Set(int)'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:576: undefined reference to `cTimeMs::Set(int)'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:555: undefined reference to `cTimeMs::Elapsed() const'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:569: undefined reference to `cTimeMs::Elapsed() const'
| /usr/src/debug/enigma2/2.7+gitAUTOINC+88e9fae8a3-r0/git/lib/driver/rclirc.cpp:571: undefined reference to `cTimeMs::Elapsed() const'

Add vdr to DEPENDS and include <tools.h> header file doesn't work due to redefinitions.

TODO: fix it on a properly way.